#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  sh build-finland-observer.sh <observer_env> [more_observer_envs...]
  sh build-finland-observer.sh all

Description:
  Builds one or more observer MQTT targets with Finland-specific defaults:
    -D RADIO_RX_ONLY_DEFAULT=1
    -D DEFAULT_AIRTIME_FACTOR=9
    -D LORA_FREQ=869.6179809
    -D LORA_BW=62.5
    -D LORA_SF=8
    -D LORA_CR=8
    -D ADVERT_NAME="FI MQTT Observer"

  Build behavior:
    - Cleans each target env before building by default.
    - Set SKIP_CLEAN=1 to skip per-env clean.

Examples:
  export FIRMWARE_VERSION=v1.0.0
  sh build-finland-observer.sh heltec_v4_repeater_observer_mqtt
  sh build-finland-observer.sh xiao_s3_wio_repeater_observer_mqtt heltec_v3_repeater_observer_mqtt
  sh build-finland-observer.sh all
EOF
}

if [ "${1:-}" = "help" ] || [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ] || [ "$#" -lt 1 ]; then
  usage
  exit 1
fi

get_observer_targets() {
  pio project config | awk '/^env:/ {print $1}' | sed 's/^env://' | awk '/repeater_observer/'
}

clean_targets() {
  local env
  for env in "$@"; do
    echo "Cleaning ${env}..."
    pio run -e "${env}" -t clean
  done
}

get_env_build_flags() {
  local env_name="$1"
  pio project config --json-output | python3 -c '
import json
import sys

target = sys.argv[1]
data = json.load(sys.stdin)
flags = []

for section, options in data:
    if section != f"env:{target}":
        continue
    for key, value in options:
        if key == "build_flags":
            if isinstance(value, list):
                flags.extend(str(v) for v in value)
            elif value is not None:
                flags.append(str(value))
            break
    break

for flag in flags:
    print(flag)
' "$env_name"
}

write_out_sidecars() {
  local env
  for env in "$@"; do
    local env_flags
    env_flags="$(get_env_build_flags "$env")"
    local sidecar_prefix=""
    local merged_prefix=""
    local artifact

    # Pick sidecar prefix from versioned artifact basename:
    # <env>-<firmware_version_and_hash>[ -merged ].<ext>
    for artifact in out/"${env}-"*; do
      [ -f "$artifact" ] || continue
      case "$artifact" in
        *.txt) continue ;;
      esac
      local base_name
      base_name="$(basename "$artifact")"
      local no_ext="${base_name%.*}"
      case "$no_ext" in
        *-merged)
          [ -z "$merged_prefix" ] && merged_prefix="${no_ext%-merged}"
          ;;
        *)
          sidecar_prefix="$no_ext"
          break
          ;;
      esac
    done

    if [ -z "$sidecar_prefix" ] && [ -n "$merged_prefix" ]; then
      sidecar_prefix="$merged_prefix"
    fi
    if [ -z "$sidecar_prefix" ]; then
      sidecar_prefix="${env}"
    fi

    local sidecar="out/${sidecar_prefix}-info.txt"
    rm -f "out/${env}-build-flags.txt"

    {
      echo "# Finland Observer Build Metadata"
      echo "#"
      echo "# This file is generated by build-finland-observer.sh"
      echo
      echo "target_env=${env}"
      echo "generated_utc=$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
      echo "script_name=build-finland-observer.sh"
      echo
      echo "# 1) Base env build_flags (from platformio.ini env:${env})"
      echo "env_build_flags_start"
      if [ -n "$env_flags" ]; then
        printf '%s\n' "$env_flags"
      else
        echo "# (none)"
      fi
      echo "env_build_flags_end"
      echo
      echo "# 2) Extra flags applied by Finland build script"
      echo "script_finland_flags=${FINLAND_FLAGS}"
      echo
      echo "# 3) Effective PLATFORMIO_BUILD_FLAGS used for build"
      echo "platformio_build_flags_env=${PLATFORMIO_BUILD_FLAGS}"
      echo
      echo "# 4) Artifacts generated in out/"
      echo "artifact_files_start"
      for artifact in out/"${env}-"*; do
        [ -f "$artifact" ] || continue
        case "$artifact" in
          *.txt) continue ;;
        esac
        echo "$(basename "$artifact")"
      done
      echo "artifact_files_end"
      echo
      echo "# 5) Important operational note"
      echo "# If you flash a merged firmware, back up your private key first."
      echo "# Restore with:"
      echo "#   set prv.key <your_64_hex_char_private_key>"
    } > "${sidecar}"
  done
}

FINLAND_FLAGS="-D RADIO_RX_ONLY_DEFAULT=1 -D DEFAULT_AIRTIME_FACTOR=9 -D LORA_FREQ=869.6179809 -D LORA_BW=62.5 -D LORA_SF=8 -D LORA_CR=8 -D ADVERT_NAME='\"FI MQTT Observer\"'"
export PLATFORMIO_BUILD_FLAGS="${PLATFORMIO_BUILD_FLAGS:-} ${FINLAND_FLAGS}"

TARGETS=()
if [ "${1:-}" = "all" ]; then
  mapfile -t TARGETS < <(get_observer_targets)
  if [ "${#TARGETS[@]}" -eq 0 ]; then
    echo "No PlatformIO environments matched: repeater_observer"
    exit 1
  fi
else
  TARGETS=("$@")
fi

if [ "${SKIP_CLEAN:-0}" != "1" ]; then
  clean_targets "${TARGETS[@]}"
fi

sh build.sh build-firmware "${TARGETS[@]}"
write_out_sidecars "${TARGETS[@]}"
